#!/usr/bin/env bash
#
# Regenerates the static regression-baseline snapshots used by Wave 0.4.
#
# Outputs (all under tests/):
#   baseline-hooks.txt              apply_filters / do_action sites in shopos-core/src
#   baseline-rest.txt               register_rest_route sites across both packages
#   baseline-cli.txt                WP_CLI::add_command sites across both packages
#   baseline-options-declared.txt   shopos_* option keys referenced by source code
#   baseline-options-legacy.txt     shopos_* option keys referenced by source code
#
# baseline-options.txt (live `wp option list` output) is captured manually
# against a real WP install and is NOT regenerated by this script.
#
# Portability: bash 3.2+ (macOS) and bash 5+ (Linux). Uses POSIX-portable
# grep -E flags and locks collation with LC_ALL=C so output is identical
# on macOS (BSD coreutils) and Linux (GNU coreutils).

set -euo pipefail
export LC_ALL=C

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd "$ROOT"

OUT="$ROOT/tests"

CORE_SRC="shopos-core/src"
DIGITAL_SRC="shopos-digital/includes"

# Hooks: apply_filters / do_action in shopos-core/src
grep -rEn --include='*.php' '(apply_filters|do_action)\s*\(' "$CORE_SRC" \
    | sort > "$OUT/baseline-hooks.txt"

# REST routes across both packages
{
    if [ -d "$CORE_SRC" ]; then
        grep -rEn --include='*.php' 'register_rest_route\s*\(' "$CORE_SRC" || true
    fi
    if [ -d "$DIGITAL_SRC" ]; then
        grep -rEn --include='*.php' 'register_rest_route\s*\(' "$DIGITAL_SRC" || true
    fi
} | sort > "$OUT/baseline-rest.txt"

# WP-CLI commands across both packages
{
    if [ -d "$CORE_SRC" ]; then
        grep -rEn --include='*.php' 'WP_CLI::add_command\s*\(' "$CORE_SRC" || true
    fi
    if [ -d "$DIGITAL_SRC" ]; then
        grep -rEn --include='*.php' 'WP_CLI::add_command\s*\(' "$DIGITAL_SRC" || true
    fi
} | sort > "$OUT/baseline-cli.txt"

# Declared identifiers: every PHP string literal (T_CONSTANT_ENCAPSED_STRING)
# under both packages whose value matches the given prefix regex. Uses PHP's
# own tokenizer via tools/extract-identifiers.php so comments and docblocks
# are never matched. Captures hook names, AJAX action slugs, transient keys,
# and nonces in addition to option keys — anything Wave 1+ must not silently
# rename. See tests/baselines/README.md.
PHP_BIN="${PHP_BIN:-php}"
EXTRACTOR="$ROOT/tools/extract-identifiers.php"

extract_identifiers() {
    local pattern="$1"
    local out_file="$2"
    {
        if [ -d "$CORE_SRC" ]; then
            "$PHP_BIN" "$EXTRACTOR" "$CORE_SRC" "$pattern"
        fi
        if [ -d "$DIGITAL_SRC" ]; then
            "$PHP_BIN" "$EXTRACTOR" "$DIGITAL_SRC" "$pattern"
        fi
    } | sort -u > "$out_file"
}

extract_identifiers 'shopos_[a-zA-Z0-9_]+' "$OUT/baseline-options-declared.txt"
extract_identifiers 'shopos_[a-zA-Z0-9_]+'  "$OUT/baseline-options-legacy.txt"
